Replace trace! with debug! calls in machine module
blockjoy/firec pull request #27
Opened 2022-08-29 15:34 UTC by loony-bean

Those logs are more important than just traces

2022-08-30 13:06 UTC, zeenix requested changes
I do agree with some of the changes but not most. As I [pointed out in the closed PR](https://github.com/blockjoy/blockvisor/pull/148#pullrequestreview-1090276040), the solution to avoid noise from irrelevant sources is to control the logging level more specifically. Upgrading our own tracing output to debug output, isn't the best way IMO.

2022-08-30 13:48 UTC, loony-bean commented
> I do agree with some of the changes but not most. As I [pointed out in the closed PR](https://github.com/blockjoy/blockvisor/pull/148#pullrequestreview-1090276040), the solution to avoid noise from irrelevant sources is to control the logging level more specifically. Upgrading our own tracing output to debug output, isn't the best way IMO.

Which `trace` calls do you think could be changed to `debug`?

2022-08-30 13:54 UTC, zeenix commented
> Which `trace` calls do you think could be changed to `debug`?

I'll comment with `+` and `-` to indicate.

2022-08-30 13:55 UTC, zeenix commented on src/machine.rs
> +        debug!("{vm_id}: Configuration: {:?}", config);
+

2022-08-30 13:56 UTC, zeenix commented on src/machine.rs
> +        debug!(
:+1:

2022-08-30 13:56 UTC, zeenix commented on src/machine.rs
> +        debug!("{vm_id}: Running command: {:?}", cmd);
:-1:

2022-08-30 13:57 UTC, zeenix commented on src/machine.rs
> +                debug!("{vm_id}: Booting the VM instance...");
:-1:

2022-08-30 13:57 UTC, zeenix commented on src/machine.rs
> +                debug!("{vm_id}: Failed to force shutdown: {}", e);
Actually I think this and the previous one should be a warning instead.

2022-08-30 13:59 UTC, zeenix commented on src/machine.rs
> +        debug!("{vm_id}: VM started successfully.");
:-1:  here too. The caller knows about the success so they can log the success on any level they prefer.

2022-08-30 13:59 UTC, zeenix commented on src/machine.rs
> +                debug!("{vm_id}: Running command: {:?}", cmd);
:-1:

2022-08-30 14:03 UTC, zeenix commented on src/machine.rs
> +        debug!("{vm_id}: Killing VM...");
:-1:

2022-08-30 14:06 UTC, zeenix commented on src/machine.rs
> +                debug!("{vm_id}: Shutdown error: {err}");
warning better here too I think.

2022-08-30 14:09 UTC, zeenix commented on src/machine.rs
> +                debug!("{vm_id}: Successfully sent KILL signal to VM (pid: `{pid}`).");
:-1:

2022-08-30 14:10 UTC, zeenix commented
It takes time to decide for each case so I'll stop now and hope my comments will help you decided. The main point is that we shouldn't just upgrade all trace to debug w/o a thought.

2022-11-04 10:06 UTC, loony-bean commented
Closing as outdated

2022-11-04 10:06 UTC, closed without merging